# Importing Satellite Datasets

In [1]:
import pandas as pd
import os
fname = '../data/campfire-gases-2018-11.csv'
trace_gases = pd.read_csv(fname)

In [2]:
trace_gases.head()

Latitude  Longitude                           Time  H2O_MR_500mb  \
0  39.693913 -120.49820  2018-11-01 10:39:44.183998108      0.001621   
1  39.996113 -121.75796  2018-11-01 10:39:44.383998871      0.001781   
2  39.248516 -120.72343  2018-11-01 10:39:52.183998108      0.001681   
3  39.547660 -121.97622  2018-11-01 10:39:52.383998871      0.001817   
4  38.802532 -120.94534  2018-11-01 10:40:00.184000015      0.001604   

   H2O_MR_850mb  CO_MR_500mb  CO_MR_850mb  O3_MR_500mb  O3_MR_850mb  \
0      0.008410     84.18882   117.011190    46.428890    22.921904   
1      0.004849     77.59622   109.939960    44.728848    21.737068   
2      0.005230     80.73684   114.791985    46.114296    22.632338   
3      0.005295     77.39363   108.182520    44.257423    21.417778   
4      0.004505     82.68274   123.891740    47.121635    22.546751   

   CH4_MR_500mb  CH4_MR_850mb  N2O_MR_500mb  N2O_MR_850mb  CO2_500mb  \
0     1842.4436     1892.8062     318.75995     320.22995  402.26596   
1     1861.1800     1891.7012     318.01180     319.45220  402.76318   
2     1861.7188     1894.3835     319.00397     320.42120  402.35360   
3     1847.3370     1889.8491     318.03134     319.47528  403.03867   
4     1890.4450     1899.3243     319.56244     320.96674  403.35144   

   CO2_850mb                       datetime  
0  402.75560  2018-11-01 10:39:44.183998108  
1  402.89474  2018-11-01 10:39:44.383998871  
2  402.72772  2018-11-01 10:39:52.183998108  
3  403.07166  2018-11-01 10:39:52.383998871  
4  403.11090  2018-11-01 10:40:00.184000015

In [3]:
trace_gases['H2O_MR_500mb']

0      0.001621
1      0.001781
2      0.001681
3      0.001817
4      0.001604
         ...   
486    0.000471
487    0.000466
488    0.000484
489    0.000289
490    0.000273
Name: H2O_MR_500mb, Length: 491, dtype: float64

In [4]:
drops = list(trace_gases.columns[5:])
print(drops)

['CO_MR_500mb', 'CO_MR_850mb', 'O3_MR_500mb', 'O3_MR_850mb', 'CH4_MR_500mb', 'CH4_MR_850mb', 'N2O_MR_500mb', 'N2O_MR_850mb', 'CO2_500mb', 'CO2_850mb', 'datetime']


In [5]:
trace_gases.drop(columns=drops, inplace=True)

In [6]:
trace_gases.head()

Latitude  Longitude                           Time  H2O_MR_500mb  \
0  39.693913 -120.49820  2018-11-01 10:39:44.183998108      0.001621   
1  39.996113 -121.75796  2018-11-01 10:39:44.383998871      0.001781   
2  39.248516 -120.72343  2018-11-01 10:39:52.183998108      0.001681   
3  39.547660 -121.97622  2018-11-01 10:39:52.383998871      0.001817   
4  38.802532 -120.94534  2018-11-01 10:40:00.184000015      0.001604   

   H2O_MR_850mb  
0      0.008410  
1      0.004849  
2      0.005230  
3      0.005295  
4      0.004505

In [7]:
from netCDF4 import Dataset
fname = '../data/aod/JRR-AOD_v1r1_npp_s201808091955538_e201808091957180_c201808092049460_thinned.nc'
file_id = Dataset(fname)

In [8]:
print(file_id)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.5
    Metadata_Conventions: CF-1.5, Unidata Dataset Discovery v1.0
    standard_name_vocabulary: CF Standard Name Table (version 17, 24 March 2011)
    project: S-NPP Data Exploitation
    institution: DOC/NOAA/NESDIS/NDE->S-NPP Data Exploitation, NESDIS, NOAA, U.S. Department of Commerce
    naming_authority: gov.noaa.nesdis.nde
    satellite_name: NPP
    instrument_name: VIIRS
    title: JPSS Risk Reduction Unique Aerosol Optical Depth
    summary: Aerosol Optical Depth
    history: VIIRS AOD Version 1.0
    processing_level: NOAA Level 2
    references: 
    id: 7e854908-1172-4d11-ae90-fb768144e6b2
    Metadata_Link: JRR-AOD_v1r1_npp_s201808091955538_e201808091957180_c201808092049460.nc
    start_orbit_number: 35149
    end_orbit_number: 35149
    day_night_data_flag: day
    ascend_descend_data_flag: 0
    time_coverage_start: 2018-08-09T19:55:53Z
    time_coverage_end: 2018

In [9]:
file_id.variables.keys()

dict_keys(['Latitude', 'Longitude', 'AOD550', 'QCAll'])

In [10]:
AOD_550 = file_id.variables['AOD550']

In [11]:
import numpy as np
AOD_550 = np.array(AOD_550)
AOD_550.shape

(768, 3200)

In [12]:
print(AOD_550)

[[-999.9 -999.9 -999.9 ... -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 ... -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 ... -999.9 -999.9 -999.9]
 ...
 [-999.9 -999.9 -999.9 ... -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 ... -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 ... -999.9 -999.9 -999.9]]


In [13]:
AOD_550.mean()

-289.06787

In [14]:
print(file_id.variables['AOD550'])

<class 'netCDF4._netCDF4.Variable'>
float32 AOD550(Rows, Columns)
    _FillValue: -999.9
    long_name: Aerosol optical depth at 550 nm
    units: 1
    valid_range: [-0.05  5.  ]
    coordinates: Longitude Latitude
unlimited dimensions: 
current shape = (768, 3200)
filling on


In [15]:
missing = file_id.variables['AOD550']._FillValue
print(missing)

-999.9


In [16]:
keep_rows = AOD_550 != missing 

AOD_550[50:60, 100], keep_rows[50:60, 100]

(array([-9.9990002e+02, -9.9990002e+02,  5.4056549e-01,  6.3157362e-01,
         1.5747026e+00,  5.9736818e-01,  6.2397045e-01,  6.7140901e-01,
         6.5959287e-01,  7.6103389e-01], dtype=float32),
 array([False, False,  True,  True,  True,  True,  True,  True,  True,
         True]))

In [17]:
AOD_550_filtered = AOD_550[keep_rows]
AOD_550_filtered

array([0.06569075, 0.08305545, 0.11872342, ..., 0.14237013, 0.16145205,
       0.14933026], dtype=float32)

In [18]:
AOD_550_filtered.mean()

0.41903266

In [19]:
AOD_550.size, AOD_550_filtered.size

(2457600, 1746384)

In [20]:
AOD550 = file_id.variables['AOD550'][:,:]
type(AOD550)

numpy.ma.core.MaskedArray

In [21]:
AOD550[50:60, 100]

masked_array(data=[--, --, 0.5405654907226562, 0.6315736174583435,
                   1.5747026205062866, 0.5973681807518005,
                   0.6239704489707947, 0.671409010887146,
                   0.659592866897583, 0.7610338926315308],
             mask=[ True,  True, False, False, False, False, False, False,
                   False, False],
       fill_value=-999.9,
            dtype=float32)

In [22]:
AOD550.mean()

0.41903259105672064

In [23]:
import h5py
fname = '../data/3B-HHR.MS.MRG.3IMERG.20170827-S120000-E122959.0720.V06B_thinned.HDF5'
file_id = h5py.File(fname, 'r')
print(file_id)

<HDF5 file "3B-HHR.MS.MRG.3IMERG.20170827-S120000-E122959.0720.V06B_thinned.HDF5" (mode r)>


In [24]:
list(file_id)

['Grid']

In [25]:
list(file_id["Grid"].keys())

['lat', 'lon', 'precipitationCal']

In [26]:
file_id.visit(print)

Grid
Grid/lat
Grid/lon
Grid/precipitationCal


In [27]:
precip = file_id["Grid/precipitationCal"][:,:,:]
precip

array([[[-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        ...,
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ]]],
      dtype=float32)

In [28]:
list(file_id["Grid/precipitationCal"].attrs)

['DimensionNames',
 'Units',
 'units',
 'coordinates',
 '_FillValue',
 'CodeMissingValue',
 'DIMENSION_LIST']

In [29]:
missing = file_id["Grid/precipitationCal"].attrs['_FillValue']
missing

-9999.9

In [30]:
PrecipMask = (precip == missing)
precip = np.ma.masked_array(precip, mask=PrecipMask)
precip

masked_array(
  data=[[[--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0],
         ...,
         [--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0]]],
  mask=[[[ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False],
         ...,
         [ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False]]],
  fill_value=1e+20,
  dtype=float32)

In [31]:
precip.mean()

0.10843209494915407

In [32]:
import pygrib

In [33]:
filename = '../data/gfsanl_3_20200501_0000_000.grb2'
gfs_grb2 = pygrib.open(filename)
records = [str(grb) for grb in gfs_grb2]

In [34]:
records[12]

'13:Temperature:K (instant):regular_ll:isobaricInPa:level 40 Pa:fcst time 0 hrs:from 202005010000'

In [35]:
temps = gfs_grb2.select(name='Temperature')
temps

[13:Temperature:K (instant):regular_ll:isobaricInPa:level 40 Pa:fcst time 0 hrs:from 202005010000,
 17:Temperature:K (instant):regular_ll:isobaricInhPa:level 100 Pa:fcst time 0 hrs:from 202005010000,
 23:Temperature:K (instant):regular_ll:isobaricInhPa:level 200 Pa:fcst time 0 hrs:from 202005010000,
 29:Temperature:K (instant):regular_ll:isobaricInhPa:level 300 Pa:fcst time 0 hrs:from 202005010000,
 35:Temperature:K (instant):regular_ll:isobaricInhPa:level 500 Pa:fcst time 0 hrs:from 202005010000,
 41:Temperature:K (instant):regular_ll:isobaricInhPa:level 700 Pa:fcst time 0 hrs:from 202005010000,
 47:Temperature:K (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 202005010000,
 54:Temperature:K (instant):regular_ll:isobaricInhPa:level 1500 Pa:fcst time 0 hrs:from 202005010000,
 58:Temperature:K (instant):regular_ll:isobaricInhPa:level 2000 Pa:fcst time 0 hrs:from 202005010000,
 65:Temperature:K (instant):regular_ll:isobaricInhPa:level 3000 Pa:fcst time 0 hrs:from 20

In [36]:
temp = gfs_grb2[315]

In [37]:
temp.values

array([[249.30024414, 249.30024414, 249.30024414, ..., 249.30024414,
        249.30024414, 249.30024414],
       [248.80024414, 248.80024414, 248.70024414, ..., 248.80024414,
        248.80024414, 248.80024414],
       [249.20024414, 249.20024414, 249.10024414, ..., 249.20024414,
        249.20024414, 249.20024414],
       ...,
       [240.00024414, 240.00024414, 240.10024414, ..., 239.70024414,
        239.80024414, 239.90024414],
       [238.40024414, 238.40024414, 238.50024414, ..., 238.40024414,
        238.40024414, 238.40024414],
       [238.40024414, 238.40024414, 238.40024414, ..., 238.40024414,
        238.40024414, 238.40024414]])

In [38]:
temp.keys()

['globalDomain',
 'GRIBEditionNumber',
 'tablesVersionLatestOfficial',
 'tablesVersionLatest',
 'grib2divider',
 'angleSubdivisions',
 'missingValue',
 'ieeeFloats',
 'isHindcast',
 'section0Length',
 'identifier',
 'discipline',
 'editionNumber',
 'totalLength',
 'sectionNumber',
 'section1Length',
 'numberOfSection',
 'centre',
 'centreDescription',
 'subCentre',
 'tablesVersion',
 'masterDir',
 'localTablesVersion',
 'significanceOfReferenceTime',
 'year',
 'month',
 'day',
 'hour',
 'minute',
 'second',
 'dataDate',
 'julianDay',
 'dataTime',
 'productionStatusOfProcessedData',
 'typeOfProcessedData',
 'md5Section1',
 'selectStepTemplateInterval',
 'selectStepTemplateInstant',
 'stepType',
 'is_chemical',
 'is_chemical_distfn',
 'is_chemical_srcsink',
 'is_aerosol',
 'is_aerosol_optical',
 'setCalendarId',
 'deleteCalendarId',
 'sectionNumber',
 'grib2LocalSectionPresent',
 'deleteLocalDefinition',
 'sectionNumber',
 'gridDescriptionSectionPresent',
 'section3Length',
 'numberOfSec

In [39]:
lat = temp.latitudes
lon = temp.longitudes
level = temp.level
units = temp.units
analysis_date = temp.analDate
fcst_time = temp.forecastTime

In [40]:
import xarray as xr

In [41]:
fname = '../data/NUCAPS-EDR_v2r0_npp_s201903031848390_e201903031849090_c201903031941100.nc'
nucaps = xr.open_dataset(fname, decode_times=False)
nucaps

<xarray.Dataset>
Dimensions:               (Number_of_CrIS_FORs: 120, Number_of_Ispares: 129,
                           Number_of_Rspares: 262, Number_of_Cloud_Layers: 8,
                           Number_of_P_Levels: 100,
                           Number_of_MW_Spectral_Pts: 16,
                           Number_of_Surf_Emis_Hinge_Pts: 100,
                           Number_of_Stability_Parameters: 16,
                           Number_of_Cloud_Emis_Hing_Pts: 100)
Coordinates:
    Time                  (Number_of_CrIS_FORs) float64 ...
    Latitude              (Number_of_CrIS_FORs) float32 ...
    Longitude             (Number_of_CrIS_FORs) float32 ...
    Pressure              (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
    Effective_Pressure    (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_CrIS_FORs, Number_of_Ispares,
                                Number_of_Rspares, Number_of_Cloud_Layers,
                                Number_of_P_Levels, Number_of_MW_Spectral_Pts,
                                Number_of_Surf_Emis_Hinge_Pts,
                                Number_of_Stability_Parameters,
                                Number_of_Cloud_Emis_Hing_Pts
Data variables: (12/64)
    quality_information   |S1 ...
    CrIS_FORs             (Number_of_CrIS_FORs) float64 ...
    View_Angle            (Number_of_CrIS_FORs) float32 ...
    Satellite_Height      (Number_of_CrIS_FORs) float32 ...
    FG_Mean_CO2           (Number_of_CrIS_FORs) float32 ...
    Mean_CO2              (Number_of_CrIS_FORs) float32 ...
    ...                    ...
    FG_IR_Surface_Emis    (Number_of_CrIS_FORs, Number_of_Surf_Emis_Hinge_Pts) float32 ...
    IR_Surface_Refl       (Number_of_CrIS_FORs, Number_of_Surf_Emis_Hinge_Pts) float32 ...
    Stability             (Number_of_CrIS_FORs, Number_of_Stability_Parameters) float32 ...
    Cloud_Freq            (Number_of_CrIS_FORs, Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
    Cloud_Emis            (Number_of_CrIS_FORs, Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
    Cloud_Refl            (Number_of_CrIS_FORs, Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
Attributes: (12/47)
    Conventions:                              CF-1.5
    Metadata_Conventions:                     CF-1.5, Unidata Datasset Discov...
    standard_name_vocabulary:                 CF Standard Name Table (version...
    project:                                  NPP Data Exploitation: NOAA NUCAPS
    title:                                    NUCAPS_L2
    summary:                                  NUCAPS retrieved profiles of te...
    ...                                       ...
    geospatial_last_scanline_first_fov_lon:   -96.39
    geospatial_last_scanline_last_fov_lon:    -75.52
    geospatial_bounds:                        POLYGON((-96.54 26.08, -88.47 2...
    instrument_resolution:                    CrIS 2211 channels
    retrieval_mode:                           IR+MW
    number_valid_fovs:                        9

In [42]:
profile = nucaps.sel(Number_of_CrIS_FORs=0)
profile

<xarray.Dataset>
Dimensions:               (Number_of_Ispares: 129, Number_of_Rspares: 262,
                           Number_of_Cloud_Layers: 8, Number_of_P_Levels: 100,
                           Number_of_MW_Spectral_Pts: 16,
                           Number_of_Surf_Emis_Hinge_Pts: 100,
                           Number_of_Stability_Parameters: 16,
                           Number_of_Cloud_Emis_Hing_Pts: 100)
Coordinates:
    Time                  float64 ...
    Latitude              float32 ...
    Longitude             float32 ...
    Pressure              (Number_of_P_Levels) float32 ...
    Effective_Pressure    (Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_Ispares, Number_of_Rspares,
                                Number_of_Cloud_Layers, Number_of_P_Levels,
                                Number_of_MW_Spectral_Pts,
                                Number_of_Surf_Emis_Hinge_Pts,
                                Number_of_Stability_Parameters,
                                Number_of_Cloud_Emis_Hing_Pts
Data variables: (12/64)
    quality_information   |S1 ...
    CrIS_FORs             float64 ...
    View_Angle            float32 ...
    Satellite_Height      float32 ...
    FG_Mean_CO2           float32 ...
    Mean_CO2              float32 ...
    ...                    ...
    FG_IR_Surface_Emis    (Number_of_Surf_Emis_Hinge_Pts) float32 ...
    IR_Surface_Refl       (Number_of_Surf_Emis_Hinge_Pts) float32 ...
    Stability             (Number_of_Stability_Parameters) float32 ...
    Cloud_Freq            (Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
    Cloud_Emis            (Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
    Cloud_Refl            (Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
Attributes: (12/47)
    Conventions:                              CF-1.5
    Metadata_Conventions:                     CF-1.5, Unidata Datasset Discov...
    standard_name_vocabulary:                 CF Standard Name Table (version...
    project:                                  NPP Data Exploitation: NOAA NUCAPS
    title:                                    NUCAPS_L2
    summary:                                  NUCAPS retrieved profiles of te...
    ...                                       ...
    geospatial_last_scanline_first_fov_lon:   -96.39
    geospatial_last_scanline_last_fov_lon:    -75.52
    geospatial_bounds:                        POLYGON((-96.54 26.08, -88.47 2...
    instrument_resolution:                    CrIS 2211 channels
    retrieval_mode:                           IR+MW
    number_valid_fovs:                        9

In [43]:
temp_profile = profile.Temperature
temp_profile

<xarray.DataArray 'Temperature' (Number_of_P_Levels: 100)>
[100 values with dtype=float32]
Coordinates:
    Time                float64 ...
    Latitude            float32 ...
    Longitude           float32 ...
    Pressure            (Number_of_P_Levels) float32 ...
    Effective_Pressure  (Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_P_Levels
Attributes:
    long_name:       Temperature
    standard_name:   air_temperature
    units:           Kelvin
    parameter_type:  NUCAPS data
    valid_range:     [   0. 1000.]

In [44]:
lat, lon = profile.Latitude.item(), profile.Longitude.item()
lat, lon

(26.224599838256836, -95.8237075805664)

In [45]:
mask = profile.Pressure.round() == 300
gradient = nucaps.sel(Number_of_P_Levels= mask)
gradient

<xarray.Dataset>
Dimensions:               (Number_of_CrIS_FORs: 120, Number_of_Ispares: 129,
                           Number_of_Rspares: 262, Number_of_Cloud_Layers: 8,
                           Number_of_P_Levels: 1,
                           Number_of_MW_Spectral_Pts: 16,
                           Number_of_Surf_Emis_Hinge_Pts: 100,
                           Number_of_Stability_Parameters: 16,
                           Number_of_Cloud_Emis_Hing_Pts: 100)
Coordinates:
    Time                  (Number_of_CrIS_FORs) float64 ...
    Latitude              (Number_of_CrIS_FORs) float32 ...
    Longitude             (Number_of_CrIS_FORs) float32 ...
    Pressure              (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
    Effective_Pressure    (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_CrIS_FORs, Number_of_Ispares,
                                Number_of_Rspares, Number_of_Cloud_Layers,
                                Number_of_P_Levels, Number_of_MW_Spectral_Pts,
                                Number_of_Surf_Emis_Hinge_Pts,
                                Number_of_Stability_Parameters,
                                Number_of_Cloud_Emis_Hing_Pts
Data variables: (12/64)
    quality_information   |S1 ...
    CrIS_FORs             (Number_of_CrIS_FORs) float64 ...
    View_Angle            (Number_of_CrIS_FORs) float32 ...
    Satellite_Height      (Number_of_CrIS_FORs) float32 ...
    FG_Mean_CO2           (Number_of_CrIS_FORs) float32 ...
    Mean_CO2              (Number_of_CrIS_FORs) float32 ...
    ...                    ...
    FG_IR_Surface_Emis    (Number_of_CrIS_FORs, Number_of_Surf_Emis_Hinge_Pts) float32 ...
    IR_Surface_Refl       (Number_of_CrIS_FORs, Number_of_Surf_Emis_Hinge_Pts) float32 ...
    Stability             (Number_of_CrIS_FORs, Number_of_Stability_Parameters) float32 ...
    Cloud_Freq            (Number_of_CrIS_FORs, Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
    Cloud_Emis            (Number_of_CrIS_FORs, Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
    Cloud_Refl            (Number_of_CrIS_FORs, Number_of_Cloud_Layers, Number_of_Cloud_Emis_Hing_Pts) float32 ...
Attributes: (12/47)
    Conventions:                              CF-1.5
    Metadata_Conventions:                     CF-1.5, Unidata Datasset Discov...
    standard_name_vocabulary:                 CF Standard Name Table (version...
    project:                                  NPP Data Exploitation: NOAA NUCAPS
    title:                                    NUCAPS_L2
    summary:                                  NUCAPS retrieved profiles of te...
    ...                                       ...
    geospatial_last_scanline_first_fov_lon:   -96.39
    geospatial_last_scanline_last_fov_lon:    -75.52
    geospatial_bounds:                        POLYGON((-96.54 26.08, -88.47 2...
    instrument_resolution:                    CrIS 2211 channels
    retrieval_mode:                           IR+MW
    number_valid_fovs:                        9

In [46]:
pres_dict = {}
for i, p in enumerate(profile.Pressure):
    if p >= 100:
        pres_dict.update({int(p): i})

In [47]:
pres_dict[300]

62

In [48]:
gradient = nucaps.sel(Number_of_P_Levels = pres_dict[300])

In [49]:
import cfgrib

In [50]:
filter_keys = {'filter_by_keys' : {'typeOfLevel': 'isobaricInhPa', 'name': 'Temperature'}}

In [51]:
filename = '../data/gfsanl_3_20200501_0000_000.grb2'
gfs = xr.open_dataset(filename, engine='cfgrib', backend_kwargs=filter_keys)
print(gfs)

Ignoring index file '../data/gfsanl_3_20200501_0000_000.grb2.08b97.idx' incompatible with GRIB file


<xarray.Dataset>
Dimensions:        (isobaricInhPa: 33, latitude: 181, longitude: 360)
Coordinates:
    time           datetime64[ns] ...
    step           timedelta64[ns] ...
  * isobaricInhPa  (isobaricInhPa) float64 1e+03 975.0 950.0 ... 3.0 2.0 1.0
  * latitude       (latitude) float64 90.0 89.0 88.0 87.0 ... -88.0 -89.0 -90.0
  * longitude      (longitude) float64 0.0 1.0 2.0 3.0 ... 357.0 358.0 359.0
    valid_time     datetime64[ns] ...
Data variables:
    t              (isobaricInhPa, latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2023-03-18T11:02 GRIB to CDM+CF via cfgrib-0.9.1...


In [52]:
temp850hpa = gfs.sel(isobaricInhPa=850)

In [53]:
temp850hpa.t.values

array([[249.30025, 249.30025, 249.30025, ..., 249.30025, 249.30025,
        249.30025],
       [248.80025, 248.80025, 248.70024, ..., 248.80025, 248.80025,
        248.80025],
       [249.20024, 249.20024, 249.10025, ..., 249.20024, 249.20024,
        249.20024],
       ...,
       [240.00024, 240.00024, 240.10025, ..., 239.70024, 239.80025,
        239.90024],
       [238.40024, 238.40024, 238.50024, ..., 238.40024, 238.40024,
        238.40024],
       [238.40024, 238.40024, 238.40024, ..., 238.40024, 238.40024,
        238.40024]], dtype=float32)

In [54]:
temp850hpa_point = gfs.sel(isobaricInhPa=850, latitude=90, longitude=0)
temp850hpa_point.t.values

array(249.30025, dtype=float32)

In [55]:
base_url = 'http://www.esrl.noaa.gov'
catalog_url = '/psd/thredds/dodsC/Datasets/noaa.ersst.v5/sst.mnmean.nc'
xr.open_dataset(base_url + catalog_url)

<xarray.Dataset>
Dimensions:    (lat: 89, lon: 180, time: 2030, nbnds: 2)
Coordinates:
  * lat        (lat) float32 88.0 86.0 84.0 82.0 ... -82.0 -84.0 -86.0 -88.0
  * lon        (lon) float32 0.0 2.0 4.0 6.0 8.0 ... 352.0 354.0 356.0 358.0
  * time       (time) datetime64[ns] 1854-01-01 1854-02-01 ... 2023-02-01
Dimensions without coordinates: nbnds
Data variables:
    time_bnds  (time, nbnds) float64 ...
    sst        (time, lat, lon) float32 ...
Attributes: (12/39)
    climatology:                     Climatology is based on 1971-2000 SST, X...
    description:                     In situ data: ICOADS2.5 before 2007 and ...
    keywords_vocabulary:             NASA Global Change Master Directory (GCM...
    keywords:                        Earth Science > Oceans > Ocean Temperatu...
    instrument:                      Conventional thermometers
    source_comment:                  SSTs were observed by conventional therm...
    ...                              ...
    comment:                         SSTs were observed by conventional therm...
    summary:                         ERSST.v5 is developed based on v4 after ...
    dataset_title:                   NOAA Extended Reconstructed SST V5
    _NCProperties:                   version=2,netcdf=4.6.3,hdf5=1.10.5
    data_modified:                   2023-03-04
    DODS_EXTRA.Unlimited_Dimension:  time